using TestProject.Common.DTO.ExecutionResult;
using TestProject.Common.Enums;
using System;
using System.Reflection;
using TestProject.SDK;

namespace TestProject.Tests.AndroidAppiumProject
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Provides an example how to run coded TestProject tests
	/// </summary>
	public class AndroidappiumprojectRunner
	{
		public static string DevToken = "k2EDITaudOQiYjlazTt3bBXl0LYcsLh5yeAKWi97hRU1";
		public static string DeviceUDID = "WCY4C18804003748";
		public static string AndroidPackage = "Your AndroidPackage";
		public static string AndroidActivity = "Your AndroidActivity";
		public static StepExecutionResult RunGKPart2()
		{
			using (var runner = RunnerFactory.Instance.CreateAndroid(DevToken, DeviceUDID, AndroidPackage, AndroidActivity))
				return runner.Run(new GKPart2(), true);
		}

		public static void Main(string[] args)
		{
			try
			{
				RunGKPart2();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex);
			}
		}
	}
}